spring:
  webflux:
    base-path: "/escambia/main"
  application:
    name: "service"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: "true"
        max_fetch_depth: "1"
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    user:
      name: "root"
      password: "root"
server:
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful
jjwt:
  secret: ")H+MbQeThWmZq4t7w!z%C*F-JaNcRfUjXn2r5u8x/A?D(G+KbPeSgVkYp3s6v9y$"
  expirationTime: 43200000
springdoc:
  webjars:
    prefix: ""
---
spring:
  config:
    activate:
      on-profile: "!dev"
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
    url: "r2dbc:postgresql://database.c7zj1xnu7zet.us-west-2.rds.amazonaws.com:5432/postgres?currentSchema=escambiadb"
    username: "postgres"
    password: "postgres"
---
spring:
  config:
    activate:
      on-profile: "dev"
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
    url: "r2dbc:postgresql://localhost:5432/postgres?currentSchema=escambiadb"
    username: "root"
    password: "Ming137137"
