services:
  main:
    image: index.docker.io/mingchang137/escambia-main:main
    ports:
      - "8081:8080"
  message:
    image: index.docker.io/mingchang137/escambia-message:main
    ports:
      - "8082:8081"
    depends_on:
      - mongo
  mongo:
    image: bitnami/mongodb:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - ALLOW_EMPTY_PASSWORD=yes
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    command: --interval 30
