services:
  main:
    image: index.docker.io/mingchang137/escambia-main:main
    ports:
      - "8081:8080"
  message:
    image: index.docker.io/mingchang137/escambia-message:main
    ports:
      - "8082:8081"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
