services:
  main:
    image: index.docker.io/mingchang137/escambia-main:main
    ports:
      - "8081:8080"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ubuntu/.docker/config.json:/config.json
    command: --interval 30
