spring:
  webflux:
    base-path: "/escambia/message"
  application:
    name: "message-service"
  data:
    mongodb:
      database: "chat"
      host: "localhost"
      port: 27017
server:
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful
  port: 8081
springdoc:
  webjars:
    prefix: ""
