spring:
  webflux:
    base-path: "/escambia/message"
  application:
    name: "message-service"
  data:
    mongodb:
      uri: "mongodb://localhost:27017/chat"
server:
  compression:
    enabled: true
  http2:
    enabled: true
  shutdown: graceful
  port: 8081
springdoc:
  webjars:
    prefix: ""
