name: chat-service CI
on:
  push:
    branches: [ main ]
    paths:
      - chat-service/**
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chat-service
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v3
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: aarch64-unknown-linux-gnu
      - name: Build with Cargo
        uses: actions-rs/cargo@v1
        with:
            use-cross: true
            command: build
            args: --release --target aarch64-unknown-linux-gnu --manifest-path chat-service/Cargo.toml
      - name: List Files
        run: ls -la
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: mingchang137/escambia-chat
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./chat-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
